[0m18:21:38.219607 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1064077f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10749cb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10749cd60>]}


============================== 18:21:38.222324 | 75ff5def-7317-4035-918b-d0775d336219 ==============================
[0m18:21:38.222324 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:21:38.222647 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init dbt_world_population', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:21:38.231950 [debug] [MainThread]: Starter project path: /Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/include/starter_project
[0m18:21:38.234905 [info ] [MainThread]: 
Your new dbt project "dbt_world_population" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:21:38.235114 [info ] [MainThread]: Setting up your profile.
[0m18:23:19.334661 [error] [MainThread]: Encountered an error:
list index out of range
[0m18:23:19.363237 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m18:23:19.378088 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 101.19471, "process_in_blocks": "0", "process_kernel_time": 0.14781, "process_mem_max_rss": "92389376", "process_out_blocks": "0", "process_user_time": 0.650334}
[0m18:23:19.378584 [debug] [MainThread]: Command `dbt init` failed at 18:23:19.378493 after 101.20 seconds
[0m18:23:19.379027 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1064077f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074fe700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107518ee0>]}
[0m18:23:19.379369 [debug] [MainThread]: Flushing usage events
[0m18:23:20.179270 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:23:25.588189 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072fc7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108188a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108188c10>]}


============================== 18:23:25.590455 | e9d88455-b757-492e-9a35-9f3fab987c3d ==============================
[0m18:23:25.590455 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:23:25.590774 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '.', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_world_population', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:23:25.598294 [info ] [MainThread]: A project called dbt_world_population already exists here.
[0m18:23:25.599047 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.043644417, "process_in_blocks": "0", "process_kernel_time": 0.073721, "process_mem_max_rss": "92241920", "process_out_blocks": "0", "process_user_time": 0.580905}
[0m18:23:25.599301 [debug] [MainThread]: Command `dbt init` succeeded at 18:23:25.599252 after 0.04 seconds
[0m18:23:25.599509 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072fc7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10817b7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108148e50>]}
[0m18:23:25.599734 [debug] [MainThread]: Flushing usage events
[0m18:23:26.244824 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:24:12.634354 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b17760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079a7940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079a7b20>]}


============================== 18:24:12.636631 | 54899256-6070-44c4-a79d-9c078a5566d5 ==============================
[0m18:24:12.636631 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:24:12.636936 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init dbt_world_population', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:24:12.644501 [debug] [MainThread]: Starter project path: /Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/include/starter_project
[0m18:24:12.647451 [info ] [MainThread]: 
Your new dbt project "dbt_world_population" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:24:12.647648 [info ] [MainThread]: Setting up your profile.
[0m18:25:11.387651 [error] [MainThread]: Encountered an error:

[0m18:25:11.418750 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:25:11.421553 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 58.81972, "process_in_blocks": "0", "process_kernel_time": 0.096668, "process_mem_max_rss": "90865664", "process_out_blocks": "0", "process_user_time": 0.600938}
[0m18:25:11.422306 [debug] [MainThread]: Command `dbt init` failed at 18:25:11.422162 after 58.82 seconds
[0m18:25:11.422718 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b17760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10798ad00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10798a7f0>]}
[0m18:25:11.422974 [debug] [MainThread]: Flushing usage events
[0m18:25:12.203255 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:27:56.704599 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076c3730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108550ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108550ca0>]}


============================== 18:27:56.706961 | 1e215a54-4879-4780-af34-23ffcf15eea2 ==============================
[0m18:27:56.706961 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:27:56.707288 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_world_population', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:27:56.715463 [debug] [MainThread]: Starter project path: /Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/include/starter_project
[0m18:27:56.718594 [info ] [MainThread]: 
Your new dbt project "dbt_world_population" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:27:56.718803 [info ] [MainThread]: Setting up your profile.
[0m18:28:12.546513 [error] [MainThread]: Encountered an error:

[0m18:28:12.571838 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:28:12.574163 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 15.902606, "process_in_blocks": "0", "process_kernel_time": 0.084748, "process_mem_max_rss": "92815360", "process_out_blocks": "0", "process_user_time": 0.601265}
[0m18:28:12.574493 [debug] [MainThread]: Command `dbt init` failed at 18:28:12.574432 after 15.90 seconds
[0m18:28:12.574771 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076c3730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108550df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108550ac0>]}
[0m18:28:12.575028 [debug] [MainThread]: Flushing usage events
[0m18:28:13.700434 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:29:15.870068 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076c4790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108553be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108553dc0>]}


============================== 18:29:15.872273 | 66862218-ea6f-4a72-a4e1-f387232327e6 ==============================
[0m18:29:15.872273 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:29:15.872582 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init dbt_world_population', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:29:15.880352 [debug] [MainThread]: Starter project path: /Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/include/starter_project
[0m18:29:15.883490 [info ] [MainThread]: 
Your new dbt project "dbt_world_population" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:29:15.883707 [info ] [MainThread]: Setting up your profile.
[0m18:29:35.092098 [error] [MainThread]: Encountered an error:

[0m18:29:35.115406 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:29:35.118102 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 19.279968, "process_in_blocks": "0", "process_kernel_time": 0.084899, "process_mem_max_rss": "92717056", "process_out_blocks": "0", "process_user_time": 0.607676}
[0m18:29:35.118700 [debug] [MainThread]: Command `dbt init` failed at 18:29:35.118570 after 19.28 seconds
[0m18:29:35.119221 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076c4790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108553dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108553be0>]}
[0m18:29:35.119749 [debug] [MainThread]: Flushing usage events
[0m18:29:36.080130 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:30:22.324923 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059b3820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a58700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a58910>]}


============================== 18:30:22.327497 | 32aaa5ca-662e-4005-8663-1de4f33fc587 ==============================
[0m18:30:22.327497 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:30:22.327822 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init dbt_population', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:30:22.335921 [debug] [MainThread]: Starter project path: /Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/include/starter_project
[0m18:30:22.338815 [info ] [MainThread]: 
Your new dbt project "dbt_population" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:30:22.339036 [info ] [MainThread]: Setting up your profile.
[0m18:31:00.012004 [error] [MainThread]: Encountered an error:

[0m18:31:00.033127 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/brunogodoy/Library/Python/3.9/lib/python/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:31:00.034601 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 37.746162, "process_in_blocks": "0", "process_kernel_time": 0.089654, "process_mem_max_rss": "91553792", "process_out_blocks": "0", "process_user_time": 0.597426}
[0m18:31:00.034886 [debug] [MainThread]: Command `dbt init` failed at 18:31:00.034818 after 37.75 seconds
[0m18:31:00.035134 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059b3820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1065358b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106a4bbe0>]}
[0m18:31:00.035363 [debug] [MainThread]: Flushing usage events
[0m18:31:01.083067 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:42:35.353734 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103b80590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047d7d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047d7c50>]}
[0m18:42:35.356036 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 18:42:35.356210 | eda1f167-b44e-4ab4-aeee-abdd9a8e83e9 ==============================
[0m18:42:35.356210 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:42:35.356447 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '.', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init dbt_world_population', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:42:35.362904 [debug] [MainThread]: Starter project path: /Users/brunogodoy/astro-dbt-venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m18:42:35.369763 [info ] [MainThread]: 
Your new dbt project "dbt_world_population" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:42:35.369980 [info ] [MainThread]: Setting up your profile.
[0m18:56:10.912430 [info ] [MainThread]: Profile dbt_world_population written to profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:56:10.940864 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 815.6537, "process_in_blocks": "0", "process_kernel_time": 0.197307, "process_mem_max_rss": "187383808", "process_out_blocks": "0", "process_user_time": 0.722855}
[0m18:56:10.942633 [debug] [MainThread]: Command `dbt init` succeeded at 18:56:10.942204 after 815.66 seconds
[0m18:56:10.944597 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x117f562c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x120019480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10470cb90>]}
[0m18:56:10.945468 [debug] [MainThread]: An error was encountered while trying to send an event
[0m18:56:10.945805 [debug] [MainThread]: Flushing usage events
[0m18:56:23.402216 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104378590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10543bd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10543bc50>]}
[0m18:56:23.404983 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 18:56:23.405175 | a8807fd6-570e-49b8-8d77-d435a3bc1bcc ==============================
[0m18:56:23.405175 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:56:23.405417 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m18:56:23.411783 [info ] [MainThread]: dbt version: 1.9.2
[0m18:56:23.411932 [info ] [MainThread]: python version: 3.13.2
[0m18:56:23.412035 [info ] [MainThread]: python path: /Users/brunogodoy/astro-dbt-venv/bin/python3.13
[0m18:56:23.412132 [info ] [MainThread]: os info: macOS-15.3.1-arm64-arm-64bit-Mach-O
[0m18:56:23.412232 [info ] [MainThread]: Using profiles dir at .
[0m18:56:23.412324 [info ] [MainThread]: Using profiles.yml file at ./profiles.yml
[0m18:56:23.412410 [info ] [MainThread]: Using dbt_project.yml file at /Users/brunogodoy/dbt-bitly/include/dbt/dbt_project.yml
[0m18:56:23.412505 [info ] [MainThread]: Configuration:
[0m18:56:23.412592 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m18:56:23.412677 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m18:56:23.412763 [info ] [MainThread]: Required dependencies:
[0m18:56:23.412881 [debug] [MainThread]: Executing "git --help"
[0m18:56:23.422300 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:56:23.422699 [debug] [MainThread]: STDERR: "b''"
[0m18:56:23.422837 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:56:23.422960 [info ] [MainThread]: Connection test skipped since no profile was found
[0m18:56:23.423143 [info ] [MainThread]: [31m2 checks failed:[0m
[0m18:56:23.423258 [info ] [MainThread]: dbt looked for a profiles.yml file in ./profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m18:56:23.423372 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/brunogodoy/dbt-bitly/include/dbt/dbt_project.yml> not found

[0m18:56:23.424763 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.050705876, "process_in_blocks": "0", "process_kernel_time": 0.096222, "process_mem_max_rss": "94765056", "process_out_blocks": "0", "process_user_time": 0.449817}
[0m18:56:23.424992 [debug] [MainThread]: Command `dbt debug` failed at 18:56:23.424945 after 0.05 seconds
[0m18:56:23.425201 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10548a8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10548a9e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105371fd0>]}
[0m18:56:23.425327 [debug] [MainThread]: An error was encountered while trying to send an event
[0m18:56:23.425423 [debug] [MainThread]: Flushing usage events
